name: Image Build

on:
    workflow_dispatch: {}

concurrency: ${{ github.workflow }}

env:
  REPOSITORY_NAME: ghcr.io/totechite/grpc-docker
  GRPC_OUTPUT_PATH: /usr/local/lib/php/extensions/grpc.so

jobs:
    php-debian:
        runs-on: [ ubuntu-24.04 ]
        strategy:
            fail-fast: false
            matrix:
                base_image:
                    # https://hub.docker.com/_/php
                    - { base_image_tag: "7.4-fpm-bullseye", os_ver: "bullseye",  glibc_ver: "2.31" }
                    - { base_image_tag: "8.0-fpm-bullseye", os_ver: "bullseye",  glibc_ver: "2.31" }
                    - { base_image_tag: "8.1-fpm-bullseye", os_ver: "bullseye",  glibc_ver: "2.31" }
                    - { base_image_tag: "8.2-fpm-bullseye", os_ver: "bullseye",  glibc_ver: "2.31" }
                    - { base_image_tag: "8.3-fpm-bullseye", os_ver: "bullseye",  glibc_ver: "2.31" }
                    - { base_image_tag: "8.1-fpm-bookworm", os_ver: "bookworm",  glibc_ver: "2.36" }
                    - { base_image_tag: "8.2-fpm-bookworm", os_ver: "bookworm",  glibc_ver: "2.36" }
                    - { base_image_tag: "8.3-fpm-bookworm", os_ver: "bookworm",  glibc_ver: "2.36" }
                grpc_ver:
                    # Refarence: https://pecl.php.net/package/grpc
                    - 1.66.0
                    - 1.65.5
                    - 1.64.1
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              context: .
              file: ./src/php/glibc/debian.Dockerfile
              build-args: |
                PHP_BASEIMAGE_TAG=${{ matrix.base_image.base_image_tag }}
                GRPC_VERSION=${{ matrix.grpc_ver }}
                GRPC_OUTPUT_PATH=${{ env.GRPC_OUTPUT_PATH }}
              cache-from: ${{ env.REPOSITORY_NAME }}:php-pecl-grpc${{ matrix.grpc_ver }}-${{ matrix.base_image.os_ver }}
              outputs: type=registry,push=true,oci-mediatypes=true,compression=zstd,compression-level=8
              tags: |
                ${{ env.REPOSITORY_NAME }}:php-pecl-grpc${{ matrix.grpc_ver }}-${{ matrix.base_image.os_ver }}
                ${{ env.REPOSITORY_NAME }}:php-pecl-grpc${{ matrix.grpc_ver }}-glibc${{ matrix.base_image.glibc_ver }}
              platforms: |
                linux/amd64
                linux/arm64
              labels: |
                glib-version="${{ matrix.base_image.glibc_ver }}"
                grpc-version="${{ matrix.base_image.grpc_ver }}"
                source="${{ github.repositoryUrl }}"
              provenance: true
